spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    validate-on-migrate: false
  datasource:
    hikari:
      keepalive-time: 0
      max-lifetime: 30000
      idle-timeout: 10000
      minimum-idle: 0
    url: jdbc:postgresql://192.168.0.197:9002/zxcvasd
    driver-class-name: org.postgresql.Driver
    username: Merfolk
    password: ferocal12093
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
