spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    clean-on-validation-error: false
    validate-on-migrate: true
  datasource:
    hikari:
      keepalive-time: 0
      max-lifetime: 7000
      idle-timeout: 4000
      minimum-idle: 0
    url: jdbc:postgresql://192.168.0.197:9002/bgfin
    driver-class-name: org.postgresql.Driver
    username: Merfolk
    password: ferocal12093
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
