spring:
  datasource:
      url: jdbc:h2:mem:testdb
      driver-class-name: org.h2.Driver
      username: sa
      password: 
  h2:
    console:
      path: /h2-console
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop 
    show-sql: false
    open-in-view: false

  profiles:
    active: console
  application:
    name: establishment

server:
  port: 8000 
  servlet:
    context-path: /api